#!/bin/sh

read -p "Clean up all branches?"
echo    

echo "git fetch"
git fetch
echo "git remote prune origin"
git remote prune origin
echo "git branch -D \$(git branch)"
git branch -D $(git branch)
echo "git branch -a"
git branch -a
