#!/bin/sh

read -p "Clean up all branches?"
echo    

echo "git fetch"
git fetch
echo "git remote prune origin"
git remote prune origin
echo "git branch | grep -v \"^*\" | xargs git branch -D"
git branch | grep -v "^*" | xargs git branch -D 
echo "git branch -a"
git branch -a
